/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registroAlumnos;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sistemas
 */
public class RegistroAlumno extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAlumno
     */
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Alumno> listaAlumnos = new ArrayList<>();

    public RegistroAlumno() {
        initComponents();
        // define el titulo de la ventana
        this.setTitle("Registro de Alumnos");
        // podemos personalizar el tamaño de la ventana
        this.setSize(620, 580);
        // de esta manera podemos colocar la ventada de manera central cuando se ejecute
        this.setLocationRelativeTo(null);

        // agregamos el nombre de las columnas 
        modelo.addColumn("Nombre");
        modelo.addColumn("Carrera");
        modelo.addColumn("Grupo");
        modelo.addColumn("Semestre");
        modelo.addColumn("promedio");
        // con este metodo agregamos el nombre de cada columna en la tabla
        refrescarTabla();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        registoAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        nCarrera = new javax.swing.JComboBox<>();
        nGrupo = new javax.swing.JComboBox<>();
        nSemestre = new javax.swing.JComboBox<>();
        spPromedio = new javax.swing.JSpinner();
        btAgregar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registoAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(registoAlumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 400, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Carrera");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Grupo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Semestre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Promedio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 260, -1));

        nCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programacion", "Ventas", "Maquinas" }));
        getContentPane().add(nCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 260, -1));

        nGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "104", "105", "106", "107", "108", "109", "201", "202", "203", "204" }));
        getContentPane().add(nGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, -1));

        nSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        getContentPane().add(nSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, -1));

        spPromedio.setModel(new javax.swing.SpinnerNumberModel(5.0d, 1.0d, 5.0d, 0.1d));
        getContentPane().add(spPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));

        btAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 90, -1));

        btBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
        try {
            Alumno x = new Alumno();
            x.setNonbre(txtNombre.getText());
            x.setCarrera(nCarrera.getSelectedItem().toString());
            x.setGrupo(Integer.parseInt(nGrupo.getSelectedItem().toString()));
            x.setSemestre(nSemestre.getSelectedItem().toString());
            x.setPromedio(Double.parseDouble(spPromedio.getValue().toString()));
            listaAlumnos.add(x);
            refrescarTabla();
        } catch (Exception e) {
            JOptionPane.showInputDialog(this, "Error al Agregar el estudiante");
        }

    }//GEN-LAST:event_btAgregarActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlumno().setVisible(true);
            }
        });
    }
    
    public void refrescarTabla() {
        // borrar todos los elementos vacio de modelo
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        for (Alumno l : listaAlumnos) {
            Object []obj = new Object[5];
            obj[0] = l.getNonbre();
            obj[1] = l.getCarrera();
            obj[2] = l.getGrupo();
            obj[3] = l.getSemestre();
            obj[4] = l.getPromedio();
            
            modelo.addRow(obj);
        }
        // se llama el nombre de la tabla y se envia el modelo ya registrado
        registoAlumnos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nCarrera;
    private javax.swing.JComboBox<String> nGrupo;
    private javax.swing.JComboBox<String> nSemestre;
    private javax.swing.JTable registoAlumnos;
    private javax.swing.JSpinner spPromedio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
